version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        SERVER_URL: "http://localhost"
    image: css_app
    container_name: css_app
    ports:
      - 80:3000
    environment:
      NODE_ENV: production
networks:
  default:
    external:
      name: ${COMPOSE_ENV-dev1}
