export const ADD_ITEMS = `ADD_ITEMS`;
export const FILTER_ITEM = `FILTER_ITEM`;
export const REMOVE_FILTER_ITEM = `REMOVE_FILTER_ITEM`;
export const UPDATE_ITEM = `UPDATE_ITEM`;
export const UPDATE_ITEM_SUCCESS = `UPDATE_ITEM_SUCCESS`;
export const UPDATE_ITEM_FAILED = `UPDATE_ITEM_FAILED`;
export const CHANGE_ITEM_VIEW = `CHANGE_ITEM_VIEW`;
export const ACTIVE_VIEW = `ACTIVE_VIEW`;
export const HISTORICAL_VIEW = `HISTORICAL_VIEW`;
export const ADD_TIME_FILTER = `ADD_TIME_FILTER`;

export const deliveryStates = {
  CREATED: `CREATED`,
  COOKED: `COOKED`,
  DRIVER_RECEIVED: `DRIVER_RECEIVED`,
  DELIVERED: `DELIVERED`,
  CANCELLED: `CANCELLED`,
};
