"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.deliveryStates = exports.CHANGE_ITEM_VIEW = exports.UPDATE_ITEM_FAILED = exports.UPDATE_ITEM_SUCCESS = exports.UPDATE_ITEM = exports.REMOVE_FILTER_ITEM = exports.FILTER_ITEM = exports.ADD_ITEMS = void 0;
const ADD_ITEMS = 'ADD_ITEMS';
exports.ADD_ITEMS = ADD_ITEMS;
const FILTER_ITEM = 'FILTER_ITEM';
exports.FILTER_ITEM = FILTER_ITEM;
const REMOVE_FILTER_ITEM = 'REMOVE_FILTER_ITEM';
exports.REMOVE_FILTER_ITEM = REMOVE_FILTER_ITEM;
const UPDATE_ITEM = 'UPDATE_ITEM';
exports.UPDATE_ITEM = UPDATE_ITEM;
const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS';
exports.UPDATE_ITEM_SUCCESS = UPDATE_ITEM_SUCCESS;
const UPDATE_ITEM_FAILED = 'UPDATE_ITEM_FAILED';
exports.UPDATE_ITEM_FAILED = UPDATE_ITEM_FAILED;
const CHANGE_ITEM_VIEW = 'CHANGE_ITEM_VIEW';
exports.CHANGE_ITEM_VIEW = CHANGE_ITEM_VIEW;
const deliveryStates = {
  CREATED: 'CREATED',
  COOKED: 'COOKED',
  DRIVER_RECEIVED: 'DRIVER_RECEIVED',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED'
};
exports.deliveryStates = deliveryStates;